# Generated by Django 4.2.1 on 2023-05-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
