# Generated by Django 4.2.1 on 2023-05-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_age_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='DOB',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
