# Generated by Django 4.2.1 on 2023-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='street_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
