# Generated by Django 4.2.1 on 2023-05-25 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customeraddress_street_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='coutry',
            new_name='country',
        ),
    ]
